# Common configuration options
#
update:
  # Seconds between checks for map update
  period: 300

#Show potential trader spawns on the map
show_potential_trader_spawn : true

# Territory Layer (Towns, Regions and Nations)
trader_layer:
  # Name of the layer
  name: "Traders"
  # List of worlds to show on the map
  # use "all" to show all worlds
  worlds:
    #  - "world"
    #  - "world_nether"
    #  - "world_the_end"
    - "all"
  # Make the layer hidden by default
  hide_by_default: false
  # ordering priority in the layer menu (low goes before high - default is 0)
  priority: 0
  # (optional) set minimum zoom level before layer is visible (0 = default, always visible)
  minimum_zoom: 0

#Landmarks layer
potential_trader_spawn_layer:
  # Name of the layer
  name: "Traders potential spawns"
  # List of worlds to show on the map
  # use "all" to show all worlds
  worlds:
    #  - "world"
    #  - "world_nether"
    #  - "world_the_end"
    - "all"
  # Make the layer hidden by default
  hide_by_default: true
  # ordering priority in the layer menu (low goes before high - default is 0)
  priority: 1
  # (optional) set minimum zoom level before layer is visible (0 = default, always visible)
  minimum_zoom: 0


# Format for popup - substitute values for macros: use %<flagname>% for value of specific flag
#%TOWN_NAME% - Name of the town
#%REGION_NAME% - Name of the region
#%DAYS_SINCE_CREATION% - Number of days since the town or region was created
#%DESCRIPTION% - Description of the town or region
#%NUMBER_CLAIMS% - Number of claims in the town or region
#%TOWN_LEADER% - Leader of the town
#%TOWN_LEVEL% - Level of the town
#%MEMBERS_LIST% - List of members in the town
#%NUMBER_OF_TOWNS% - Number of towns in the region
#%TOWN_LIST% - List of towns in the region
#%REGION_CAPITAL% - Capital of the region

trader_infowindow: '<div class="infowindow"><span style="font-size:140%;font-weight:bold;">%TRADER_NAME%</span><br><span style="font-size:80%">Will leave in %NB_HOURS_BEFORE_NEXT_POSITION% hours(s)</span><br><br><b>Sells</b><br>%ALL_TRADES%</div>'
